import 'package:easy_localization/easy_localization.dart';
import 'package:budgie_breeding_tracker/domain/services/genetics/mutation_database.dart';

typedef _Translate = String Function(String key);

/// Localizes free-form phenotype labels generated by the genetics engine.
abstract final class PhenotypeLocalizer {
  static final List<(String, String)> _phraseKeys = _buildPhraseKeys();

  static List<(String, String)> _buildPhraseKeys() {
    final seen = <String>{};
    final phrases = <(String, String)>[];

    void add(String phrase, String key) {
      final normalized = phrase.toLowerCase();
      if (seen.add(normalized)) {
        phrases.add((phrase, key));
      }
    }

    for (final (phrase, key) in [
      ('PallidIno (Lacewing)', 'genetics.phenotype_pallidino_lacewing'),
      (
        'Melanistic Double Factor Spangle',
        'genetics.phenotype_melanistic_double_factor_spangle',
      ),
      (
        'Single Factor Anthracite',
        'genetics.phenotype_single_factor_anthracite',
      ),
      (
        'Double Factor Anthracite',
        'genetics.phenotype_double_factor_anthracite',
      ),
      ('Double Factor Spangle', 'genetics.phenotype_double_factor_spangle'),
      ('Melanistic Spangle', 'genetics.phenotype_melanistic_spangle'),
      ('Double Dominant Pied', 'genetics.phenotype_double_dominant_pied'),
      ('Dutch Clearflight Pied', 'genetics.phenotype_dutch_clearflight_pied'),
      ('Full-Body Greywing', 'genetics.mutation_fullbody_greywing'),
      ('Dark-Eyed Clear', 'genetics.dark_eyed_clear'),
      ('Visual Violet', 'genetics.phenotype_visual_violet'),
      ('Yellowface Type I Blue', 'genetics.phenotype_yellowface_type1_blue'),
      ('Yellowface Type II Blue', 'genetics.phenotype_yellowface_type2_blue'),
      ('Yellowface Type II DF', 'genetics.phenotype_yellowface_type2_df'),
      ('Blue Factor I Blue', 'genetics.phenotype_blue_factor1_blue'),
      ('Blue Factor II Blue', 'genetics.phenotype_blue_factor2_blue'),
      ('Goldenface Blue', 'genetics.phenotype_goldenface_blue'),
      ('Turquoise Blue', 'genetics.phenotype_turquoise_blue'),
      ('Aqua Blue', 'genetics.phenotype_aqua_blue'),
      ('Turquoise Aqua', 'genetics.phenotype_turquoise_aqua'),
      ('Half-Circular Crest', 'genetics.phenotype_half_circular_crest'),
      ('Full-Circular Crest', 'genetics.phenotype_full_circular_crest'),
      ('Pallid Texas Clearbody', 'genetics.phenotype_pallid_texas_clearbody'),
      ('English Fallow', 'genetics.mutation_fallow_english'),
      ('German Fallow', 'genetics.mutation_fallow_german'),
      ('Light Green', 'genetics.phenotype_light_green'),
      ('Dark Green', 'genetics.phenotype_dark_green'),
      ('Grey-Green', 'genetics.phenotype_grey_green'),
      ('Skyblue', 'genetics.phenotype_skyblue'),
      ('Cobalt', 'genetics.phenotype_cobalt'),
      ('Mauve', 'genetics.phenotype_mauve'),
      ('Olive', 'genetics.phenotype_olive'),
      ('Tufted', 'genetics.phenotype_tufted'),
      ('Lacewing', 'genetics.mutation_lacewing'),
      ('Whitefaced', 'genetics.whitefaced'),
      ('Creamino', 'genetics.creamino'),
      ('Albino', 'genetics.mutation_albino'),
      ('Lutino', 'genetics.mutation_lutino'),
      ('Normal', 'genetics.mutation_normal'),
      ('Green', 'genetics.mutation_green'),
    ]) {
      add(phrase, key);
    }

    for (final record in MutationDatabase.getAll()) {
      add(record.name, record.localizationKey);
    }

    phrases.sort((a, b) => b.$1.length.compareTo(a.$1.length));
    return phrases;
  }

  /// Localize a phenotype label (compound or simple) to current locale.
  static String localizePhenotype(
    String raw, {
    String Function(String key)? translate,
  }) {
    final t = translate ?? _defaultTranslate;
    final input = raw.trim();
    if (input.isEmpty) return raw;

    final listCarrierPattern = RegExp(
      r'^(.*?)\s*\((.*?)\s+carrier\)$',
      caseSensitive: false,
    );
    final listCarrier = listCarrierPattern.firstMatch(input);
    if (listCarrier != null) {
      final base = localizePhenotype(listCarrier.group(1)!, translate: t);
      final localizedCarrierList = _splitMutationList(
        listCarrier.group(2)!,
      ).map((name) => localizeMutation(name, translate: t)).join(', ');
      return '$base ($localizedCarrierList ${t('genetics.carrier').toLowerCase()})';
    }

    final simpleCarrierPattern = RegExp(
      r'^(.*?)\s*\(carrier\)$',
      caseSensitive: false,
    );
    final simpleCarrier = simpleCarrierPattern.firstMatch(input);
    if (simpleCarrier != null) {
      final base = localizePhenotype(simpleCarrier.group(1)!, translate: t);
      return '$base (${t('genetics.carrier').toLowerCase()})';
    }

    var localized = input;
    localized = localized.replaceAllMapped(
      RegExp(r'\(single\)', caseSensitive: false),
      (_) => '(${t('genetics.phenotype_single')})',
    );
    localized = localized.replaceAllMapped(
      RegExp(r'\(double\)', caseSensitive: false),
      (_) => '(${t('genetics.phenotype_double')})',
    );
    localized = localized.replaceAllMapped(
      RegExp(r'\(homozygous\)', caseSensitive: false),
      (_) => '(${t('genetics.phenotype_homozygous')})',
    );

    if (localized.contains('/')) {
      return localized
          .split('/')
          .map((part) => localizeMutation(part.trim(), translate: t))
          .join(' / ')
          .replaceAll(RegExp(r'\s{2,}'), ' ')
          .trim();
    }

    return _replaceKnownPhrases(localized, t);
  }

  /// Localize mutation names or IDs (e.g., "blue", "Blue", "Dark Factor").
  static String localizeMutation(
    String raw, {
    String Function(String key)? translate,
  }) {
    final t = translate ?? _defaultTranslate;
    final input = raw.trim();
    if (input.isEmpty) return raw;

    final byId = MutationDatabase.getById(input);
    if (byId != null) return t(byId.localizationKey);

    final byName = MutationDatabase.getByName(input);
    if (byName != null) return t(byName.localizationKey);

    return _replaceKnownPhrases(input, t);
  }

  /// Localize a list of mutation names/IDs.
  static List<String> localizeMutationList(
    Iterable<String> names, {
    String Function(String key)? translate,
  }) {
    final t = translate ?? _defaultTranslate;
    return names.map((n) => localizeMutation(n, translate: t)).toList();
  }

  static String _replaceKnownPhrases(String input, _Translate t) {
    var localized = input;
    var placeholderIndex = 0;
    final placeholderValues = <String, String>{};

    for (final (phrase, key) in _phraseKeys) {
      final pattern = RegExp(
        '(?<![A-Za-z0-9_])${RegExp.escape(phrase)}(?![A-Za-z0-9_])',
        caseSensitive: false,
      );
      localized = localized.replaceAllMapped(pattern, (_) {
        final placeholder = '__PHENO_PLACEHOLDER_${placeholderIndex++}__';
        placeholderValues[placeholder] = t(key);
        return placeholder;
      });
    }

    for (final entry in placeholderValues.entries) {
      localized = localized.replaceAll(entry.key, entry.value);
    }

    return localized.replaceAll(RegExp(r'\s{2,}'), ' ').trim();
  }

  static List<String> _splitMutationList(String rawList) {
    return rawList
        .split(',')
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList();
  }

  /// Localize mutation IDs from a stored genotype map to display names.
  static List<String> localizeGenotypeKeys(Map<String, String> genotype) {
    return genotype.keys.map((id) {
      final record = MutationDatabase.getById(id);
      return record?.localizationKey.tr() ?? localizeMutation(id);
    }).toList();
  }

  static String _defaultTranslate(String key) => key.tr();
}
