-- Normalize fresh-project ACLs to the production-authoritative privilege
-- snapshot captured on 2026-07-31. This closes broad platform defaults such
-- as anon/authenticated TRUNCATE and TRIGGER grants on replayed tables.

REVOKE ALL PRIVILEGES ON SCHEMA "public" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA "public" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "public" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "public" FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL PRIVILEGES ON SCHEMA "private" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA "private" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "private" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "private" FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL PRIVILEGES ON SCHEMA "internal" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA "internal" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "internal" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA "internal" FROM PUBLIC, anon, authenticated, service_role;

GRANT USAGE ON SCHEMA "internal" TO "authenticated";
GRANT USAGE ON SCHEMA "internal" TO "service_role";
GRANT USAGE ON SCHEMA "private" TO "authenticated";
GRANT USAGE ON SCHEMA "private" TO "service_role";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "private"."edge_rate_limits" TO "service_role";
GRANT INSERT, MAINTAIN, REFERENCES, SELECT ON TABLE "public"."admin_logs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admin_logs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."admin_rate_limits" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admin_rate_limits" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."admin_sessions" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admin_sessions" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."admin_users" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admin_users" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."archive_jobs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."archive_jobs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."archive_settings" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."archive_settings" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."archived_birds" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."archived_birds" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."archived_breeding_pairs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."archived_breeding_pairs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."archived_chicks" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."archived_chicks" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."archived_clutches" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."archived_clutches" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."archived_eggs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."archived_eggs" TO "service_role";
GRANT DELETE, SELECT, UPDATE ON TABLE "public"."audit_logs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."audit_logs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."backup_history" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."backup_history" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."backup_jobs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."backup_jobs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."backup_settings" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."backup_settings" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."badges" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."badges" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."badges" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."birds" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."birds" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."breeding_pairs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."breeding_pairs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."calendar" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."calendar" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."chicks" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."chicks" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."clutches" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."clutches" TO "service_role";
GRANT DELETE, INSERT, SELECT ON TABLE "public"."community_blocks" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_blocks" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_bookmarks" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_bookmarks" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_comment_likes" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_comment_likes" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_comments" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_comments" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_event_attendees" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_event_attendees" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_events" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_events" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_follows" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_follows" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_follows" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_likes" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_likes" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_mutes" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_mutes" TO "service_role";
GRANT SELECT ON TABLE "public"."community_poll_options" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_poll_options" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_poll_options" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_poll_votes" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_poll_votes" TO "service_role";
GRANT SELECT ON TABLE "public"."community_polls" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_polls" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_polls" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT ON TABLE "public"."community_posts" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_posts" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_reports" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_reports" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_reports" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_stories" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_stories" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."community_story_views" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_story_views" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."config_backups" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."config_backups" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversation_participants" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversation_participants" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversation_participants" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversations" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversations" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."conversations" TO "service_role";
GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."db_monitoring_snapshots_id_seq" TO "anon";
GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."db_monitoring_snapshots_id_seq" TO "authenticated";
GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."db_monitoring_snapshots_id_seq" TO "service_role";
GRANT DELETE, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."db_monitoring_snapshots" TO "anon";
GRANT DELETE, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."db_monitoring_snapshots" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."db_monitoring_snapshots" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."deleted_eggs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."deleted_eggs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."egg_archives" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."egg_archives" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."eggs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."eggs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."error_logs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."error_logs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."event_reminders" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_reminders" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."event_templates" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_templates" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."event_types" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."event_types" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."events" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."events" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."fcm_tokens" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."fcm_tokens" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."feedback" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."feedback" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."genetics_history" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."genetics_history" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."growth_measurements" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."growth_measurements" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."health_records" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."health_records" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."incubations" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."incubations" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."marketplace_favorites" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."marketplace_favorites" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."marketplace_favorites" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."marketplace_listings" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."marketplace_listings" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."marketplace_listings" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."messages" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."messages" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."messages" TO "service_role";
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."mfa_lockouts" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mfa_lockouts" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mfa_recovery_codes" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mfa_recovery_codes" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."mfa_recovery_codes" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."nests" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."nests" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."notification_history" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notification_history" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."notification_rate_limits" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notification_rate_limits" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."notification_schedules" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notification_schedules" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."notification_settings" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notification_settings" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."notifications" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notifications" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."photos" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."photos" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."privacy_audit_logs" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."privacy_audit_logs" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."privacy_settings" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."privacy_settings" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."profiles" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."security_events" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."security_events" TO "service_role";
GRANT SELECT ON TABLE "public"."subscription_plans" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."subscription_plans" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."subscription_plans" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."sync_metadata" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sync_metadata" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."system_alerts" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."system_alerts" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."system_metrics" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."system_metrics" TO "service_role";
GRANT SELECT ON TABLE "public"."system_settings" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."system_settings" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."system_settings" TO "service_role";
GRANT SELECT ON TABLE "public"."system_status" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."system_status" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."system_status" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_badges" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_badges" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_badges" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_levels" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_levels" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_levels" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."user_preferences" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_preferences" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."user_sessions" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_sessions" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_streaks" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_streaks" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_streaks" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."user_subscriptions" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_subscriptions" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, UPDATE ON TABLE "public"."web_push_subscriptions" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."web_push_subscriptions" TO "service_role";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."xp_transactions" TO "anon";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."xp_transactions" TO "authenticated";
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."xp_transactions" TO "service_role";

GRANT EXECUTE ON FUNCTION "internal"."apply_community_report_aggregation"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."apply_community_report_aggregation"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."enforce_community_post_guards"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."enforce_community_post_guards"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."flag_community_post_on_edit"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."flag_community_post_on_edit"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."flag_marketplace_listing_on_edit"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."flag_marketplace_listing_on_edit"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."fn_audit_profile_role_change"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."fn_audit_profile_role_change"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."fn_audit_row_change"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."fn_audit_row_change"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."guard_conversations_update"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."guard_conversations_update"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."guard_marketplace_listings_update"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."guard_marketplace_listings_update"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."guard_messages_update"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."guard_messages_update"() TO "service_role";
GRANT EXECUTE ON FUNCTION "internal"."guard_participants_update"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "internal"."guard_participants_update"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_bulk_delete_user_data"(uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_bulk_delete_user_data"(uuid[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_clean_soft_deleted_records"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_clean_soft_deleted_records"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_chicks"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_chicks"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_eggs"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_eggs"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_health_records"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_health_records"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_reminders"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_count_orphan_reminders"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_dismiss_security_event"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_dismiss_security_event"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_export_all_tables"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_export_all_tables"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_export_table"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_export_table"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_force_logout"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_force_logout"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_get_build_distribution"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_get_build_distribution"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_get_stats"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_get_stats"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_get_table_counts"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_get_table_counts"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_grant_premium"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_grant_premium"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_log_user_data_export"(uuid, jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_log_user_data_export"(uuid, jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_moderate_community_content"(text, uuid, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_moderate_community_content"(text, uuid, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_all_user_data"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_all_user_data"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_stuck_sync_records"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_stuck_sync_records"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_system_settings"(jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_system_settings"(jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_table"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_reset_table"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_revoke_premium"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_revoke_premium"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_send_bulk_notification"(uuid[], text, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_send_bulk_notification"(uuid[], text, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_send_notification"(uuid, text, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_send_notification"(uuid, text, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_set_user_active"(uuid, boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_set_user_active"(uuid, boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_top_users"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_top_users"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_update_bulk_notification_delivery"(uuid[], boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_update_bulk_notification_delivery"(uuid[], boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_update_feedback"(uuid, text, text, text, text, uuid, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_update_feedback"(uuid, text, text, text, text, uuid, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_update_notification_delivery"(uuid, boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_update_notification_delivery"(uuid, boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."admin_update_system_setting"(text, jsonb, text, boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."admin_update_system_setting"(text, jsonb, text, boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."assert_target_user_mutable"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."assert_target_user_mutable"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."check_community_post_allowed_for_user"(uuid, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."check_community_post_allowed_for_user"(uuid, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."check_community_post_allowed"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."check_community_post_allowed"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."claim_fcm_token"(uuid, text, text, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."claim_fcm_token"(uuid, text, text, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."conversation_has_block_with"(uuid, uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "private"."count_active_birds"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."count_active_breeding_pairs"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."count_active_incubations"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."enforce_xp_daily_limit"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "private"."get_leaderboard"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."get_leaderboard"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."get_own_profile_sensitive_fields"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."get_own_profile_sensitive_fields"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."get_poll_results"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."get_poll_results"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."get_server_capacity"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."get_server_capacity"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."increment_marketplace_listing_view"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."increment_marketplace_listing_view"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."is_admin"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."is_admin"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."is_conversation_creator"(uuid, uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "private"."is_conversation_manager"(uuid, uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "private"."is_conversation_member"(uuid, uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."is_conversation_member"(uuid, uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."is_premium_or_privileged"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."is_premium_or_privileged"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."log_admin_action"(uuid, text, uuid, text, uuid, jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."log_admin_action"(uuid, text, uuid, text, uuid, jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."meets_verified_breeder_criteria"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."notify_founders_of_feedback"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."notify_founders_of_feedback"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."record_daily_checkin"(uuid, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."record_daily_checkin"(uuid, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."redeem_mfa_recovery_code"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."request_account_deletion"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."request_account_deletion"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."require_active_admin"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."require_active_admin"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."require_founder"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."require_founder"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."reset_user_data"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."reset_user_data"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."sender_blocked_in_conversation"(uuid, uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "private"."streak_bonus_for"(integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "private"."verify_monitoring_cron_jobs"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."verify_monitoring_cron_jobs"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."verify_rls_profiles_update_guards"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."verify_rls_profiles_update_guards"() TO "service_role";
GRANT EXECUTE ON FUNCTION "private"."xp_action_amount"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."xp_calculate_level"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "private"."xp_daily_limit"(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "private"."xp_title_for_level"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_bulk_delete_user_data"(uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_bulk_delete_user_data"(uuid[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_clean_soft_deleted_records"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_clean_soft_deleted_records"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_chicks"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_chicks"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_eggs"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_eggs"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_health_records"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_health_records"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_reminders"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_count_orphan_reminders"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_dismiss_security_event"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_dismiss_security_event"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_export_all_tables"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_export_all_tables"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_export_table"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_export_table"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_force_logout"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_force_logout"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_get_build_distribution"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_get_build_distribution"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_get_stats"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_get_stats"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_get_table_counts"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_get_table_counts"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_get_user_aggregate_detail"(uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."admin_get_user_aggregate_detail"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_get_user_aggregate_detail"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_grant_premium"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_grant_premium"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_log_user_data_export"(uuid, jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_log_user_data_export"(uuid, jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_moderate_community_content"(text, uuid, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_moderate_community_content"(text, uuid, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_all_user_data"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_all_user_data"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_stuck_sync_records"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_stuck_sync_records"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_system_settings"(jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_system_settings"(jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_table"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_reset_table"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_revoke_premium"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_revoke_premium"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_send_bulk_notification"(uuid[], text, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_send_bulk_notification"(uuid[], text, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_send_notification"(uuid, text, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_send_notification"(uuid, text, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_set_user_active"(uuid, boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_set_user_active"(uuid, boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_top_users"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_top_users"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_update_bulk_notification_delivery"(uuid[], boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_update_bulk_notification_delivery"(uuid[], boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_update_feedback"(uuid, text, text, text, text, uuid, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_update_feedback"(uuid, text, text, text, text, uuid, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_update_notification_delivery"(uuid, boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_update_notification_delivery"(uuid, boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."admin_update_system_setting"(text, jsonb, text, boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."admin_update_system_setting"(text, jsonb, text, boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."apply_verified_premium_status"(uuid, boolean, text, timestamp with time zone, timestamp with time zone, text, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."capture_connection_stats"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."capture_slow_queries"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."capture_table_health"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."check_community_post_allowed"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."check_community_post_allowed"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."check_edge_rate_limit"(text, integer, integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."claim_fcm_token"(uuid, text, text, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."claim_fcm_token"(uuid, text, text, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."cleanup_expired_backups"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."cleanup_expired_rate_limits"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."cleanup_monitoring_data"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."custom_access_token_hook"(jsonb) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."enforce_community_post_guards"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."fetch_community_feed"(integer, timestamp with time zone, uuid, text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."fetch_community_feed"(integer, timestamp with time zone, uuid, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."fetch_community_feed"(integer, timestamp with time zone, uuid, text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."fetch_user_post_social_state"(uuid, uuid[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."fetch_user_post_social_state"(uuid, uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."fetch_user_post_social_state"(uuid, uuid[]) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."fetch_user_post_social_state"(uuid, uuid[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."fn_audit_profile_role_change"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."fn_audit_row_change"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_community_posts_by_tag"(text, integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_community_posts_by_tag"(text, integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_community_posts_by_tag"(text, integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."get_community_posts_by_tag"(text, integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_entity_counts"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_entity_counts"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_leaderboard"(integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_leaderboard"(integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_own_profile_sensitive_fields"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_own_profile_sensitive_fields"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_poll_results"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_poll_results"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_server_capacity"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_server_capacity"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."guard_protected_role_premium_mutation"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."guard_protected_role_premium_mutation"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."guard_protected_role_premium_mutation"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."guard_protected_role_premium_mutation"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."increment_marketplace_listing_view"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."increment_marketplace_listing_view"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."is_conversation_member"(uuid, uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."is_conversation_member"(uuid, uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."is_premium_or_privileged"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."is_premium_or_privileged"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."mark_message_read"(uuid, uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."mark_message_read"(uuid, uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."notify_founders_of_feedback"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."notify_founders_of_feedback"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."prevent_self_community_report"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."propagate_user_id_from_clutch"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."protect_profile_sensitive_fields"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."record_daily_checkin"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_daily_checkin"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."redeem_mfa_recovery_code"(text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."redeem_mfa_recovery_code"(text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."redeem_mfa_recovery_code"(text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."request_account_deletion"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."request_account_deletion"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."reset_user_data"(uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."reset_user_data"(uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."run_scheduled_cleanup"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."set_admin_log_ip"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."set_admin_log_ip"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_admin_log_ip"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."set_admin_log_ip"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."sync_admin_role_to_profile"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."sync_display_name_from_full_name"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."sync_display_name_from_full_name"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_display_name_from_full_name"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."sync_display_name_from_full_name"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."sync_marketplace_listing_profile"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."sync_marketplace_listing_profile"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_marketplace_listing_profile"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."sync_marketplace_listing_profile"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."sync_poll_vote_counts"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."sync_premium_status"(boolean, text, timestamp with time zone, text, timestamp with time zone) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."sync_profile_role_to_admin_users"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_comment_like_count"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_comment_reply_count"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_conversation_last_message"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."update_conversation_last_message"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_conversation_last_message"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."update_conversation_last_message"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_conversation_participant_count"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."update_conversation_participant_count"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_conversation_participant_count"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."update_conversation_participant_count"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_conversations_updated_at"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."update_conversations_updated_at"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_conversations_updated_at"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."update_conversations_updated_at"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_marketplace_listings_updated_at"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."update_marketplace_listings_updated_at"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_marketplace_listings_updated_at"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."update_marketplace_listings_updated_at"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_post_comment_count"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_post_like_count"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."update_updated_at"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."update_updated_at"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_updated_at"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."update_updated_at"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."validate_bird_parent_integrity"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."validate_bird_parent_integrity"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."validate_bird_parent_integrity"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."validate_bird_parent_integrity"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."validate_breeding_pair_integrity"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."validate_breeding_pair_integrity"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."validate_breeding_pair_integrity"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."validate_breeding_pair_integrity"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."validate_community_comment_parent"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."verify_monitoring_cron_jobs"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."verify_monitoring_cron_jobs"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."verify_rls_profiles_update_guards"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."verify_rls_profiles_update_guards"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."weekly_stats_reset"() TO "service_role";

-- Normalize defaults used by later forward migrations.
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL PRIVILEGES ON SEQUENCES FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL PRIVILEGES ON FUNCTIONS FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL PRIVILEGES ON TABLES FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT EXECUTE ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "service_role";
